### ISSUE TITLE
gradle daemon incompatibility since 2019.1

### ISSUE THREAD

**Issue by skiedrowski** [mictaege/spoon-gradle-plugin#28]
since updating to 2019.1

    ./gradlew clean buildLocalDevEnv --rerun-tasks

sometimes leads to

    > Task :xxx:spoonMain FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':xxx:spoonMain'.
    > PROJECT_DIR/xxx/build/libs/xxx-NEXT-SNAPSHOT.jar does not exist, it is not a valid folder

since compile runs after spoonMain, it seems reasonable that there is no xxx-NEXT-SNAPSHOT.jar.

# Workaround
stop gradle daemon
---
Stacktrace:

    14:09:32.795 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: spoon.compiler.InvalidClassPathException: PROJECT_DIR/xxx/build/libs/xxx-NEXT-SNAPSHOT.jar does not exist, it is not a valid folder
    14:09:32.795 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at spoon.support.StandardEnvironment.verifySourceClasspath(StandardEnvironment.java:447)
    14:09:32.795 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at spoon.support.StandardEnvironment.setSourceClasspath(StandardEnvironment.java:437)
    14:09:32.795 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at spoon.support.StandardEnvironment.setInputClassLoader(StandardEnvironment.java:392)
    14:09:32.795 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at spoon.compiler.Environment$setInputClassLoader.call(Unknown Source)
    14:09:32.795 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.mictaege.spoon_gradle_plugin.SpoonTask.runSpoon(SpoonTask.groovy:79)
    14:09:32.795 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.mictaege.spoon_gradle_plugin.SpoonTask.run(SpoonTask.groovy:39)
    14:09:32.795 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 88 more

**Comment by mictaege** [comment]
resolved with #30
